<div class="container" style="margin-top:10px;">
	<div class="jumbotron">
		<h1><?=$this->translate('hello');?>, ZF3!</h1>
		<p>...</p>
		<p><a class="btn btn-primary btn-lg" href="<?=$this->url('home');?><?=$this->lang;?>/user/" role="button"><?=$this->translate('learn more');?></a></p>
		<p><a class="btn btn-success btn-lg" href="<?=$this->url('home');?><?=$this->lang;?>/map/" role="button">Goto Map</a></p>
		<p><a class="btn btn-warning btn-lg" href="<?=$this->url('home');?><?=$this->lang;?>/test/" role="button">Goto Test</a></p>
	</div>
</div>