<div class="container" style="margin-top:10px;">
  
  <div class="bs-callout bs-callout-primary">
    <form action="?act=question1" method="post">
      <h4>Find X from Array [3, 5, 9, 15, X]</h4>
      <button type="submit" class="btn btn-info">Calculate</button>
      <span>Result is: <?= $this->answer1 ?></span>
    </form>
  </div>

  <div class="bs-callout bs-callout-success">
    <form action="?act=question2" method="post">
      <h4>Find X from  (X + 24) + (10 × 2) = 99</h4>
      <button type="submit" class="btn btn-success">Calculate</button>
      <span>Result is: <?= $this->answer2 ?></span>
    </form>
  </div>
  
</div>